name: 2.8.x on PHP 5.3

# Run this workflow every time a new commit pushed to your repository
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  push:
    branches: ['2.8.x']
  pull_request:
    branches: ['2.8.x']

jobs:
  run:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        php-version: ["5.3"]
        os: ['ubuntu-latest']
        include:
          - os: 'ubuntu-latest'
            php-version: '5.3'
            phpunit-version: '4.8.36'
            composer-version: 'v1'
          - os: 'ubuntu-latest'
            php-version: '7.4'
            phpunit-version: '4.8.36'
            composer-version: 'latest'
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup PHP ${{ matrix.php-version }} on ${{ matrix.os }}
        uses: shivammathur/setup-php@verbose
        with:
          php-version: ${{ matrix.php-version }}
          extensions: mbstring, intl
          ini-values: post_max_size=256M, max_execution_time=180
          coverage: xdebug
          tools: phpunit:${{ matrix.phpunit-version }}, composer:${{ matrix.composer-version }}

      - name: Run tests
        run: phpunit -v -c tests/phpunit.xml --coverage-text --strict-coverage --stop-on-risky
        shell: bash

      - name: Slack Notification
        uses: 8398a7/action-slack@v3
        with:
          status: custom
          fields: commit,repo,ref,author
          custom_payload: |
            {
              attachments: [{
                color: '${{ job.status }}' === 'success' ? 'good' : '${{ job.status }}' === 'failure' ? 'danger' : 'warning',
                text: `${process.env.AS_AUTHOR} has pushed ${process.env.AS_COMMIT} in ${process.env.AS_REPO} with test status indicating ${{ job.status }}.`,
              }]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          MATRIX_CONTEXT: ${{ toJson(matrix) }}
        if: always() # Pick up events even if the job fails or is canceled.
